---
title: "Sign Up"
---

<!-- https://forms.gle/uqqJvR4VhM1YuKCR8 -->

### Participants

<!-- Registration to participate in DataFest 2024 @ Duke is not yet open. Please check back soon! -->

<!-- :::callout-important -->

<!-- **Registration as a participant for DataFest 2023 has closed. The event is at capacity.** -->

<!-- ::: -->

Click on the option that applies to you. Regardless of the option you choose, you will automatically be placed on the ASA DataFest<sup>TM</sup> mailing list to receive updates and announcements.

::: callout-note
**The registration deadline is 5PM February 23, 2024. Seats are limited, so sign up before it's too late!**
:::

**Option 1: Team sign-up (2-5 students)**

Click [here](https://forms.gle/vvnr33WDAx848p4K8) to sign up as a team of 2 to 5 students.

**Option 2: Looking for teammates**

If you do not have a team in mind but you're looking for teammates, click [here](https://forms.gle/fKJhRC1rUgmsfvQp6) to leave us your information so that you can be matched with others.

### Consultants

If you are interested in serving as a consultant during the event, please let us know your availability [here](https://forms.gle/iMf1c3Nggna9mTJcA).

### Questions

If you have any questions about your registration, please contact [Prof. Alexander Fisher](mailto:aaf29@duke.edu).
